name: Docke0

on:
  push:
    branches:
      - main # Se ejecuta cuando hay un push a la rama main
  workflow_dispatch: # Se ejecuta cuando se hace un disparo manual

jobs:
  docker-login:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Login a Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: karlostcp
          password: ${{ secrets.MI_PTA_DOCKERHUB2 }}

      # Paso 3: Crear la imagen de Docker
      - name: Build Docker Image
        run: |
          docker build -t karlostcp/ubuntu-image:1.0.0 .

      # Paso 4: Subir la imagen a Docker Hub
      - name: Push Docker Image
        run: |
          docker push karlostcp/ubuntu-image:1.0.0


