name:  Docker2

on:
  push:
    branches:
      - main # Se ejecuta cuando hay un push a la rama main
  workflow_dispatch: # Se ejecuta cuando se hace un disparo manual

jobs:
  docker-login:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio karlosdocker/my-ecomerce-front
      - name: Checkout code from karlosdocker/my-ecomerce-front
        uses: actions/checkout@v3
        with:
          repository: karlosdocker/my-ecomerce-front  # Especificar el repositorio donde está el Dockerfile


      # Paso 2: Login a Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: karlostcp
          password: ${{ secrets.MI_PTA_DOCKERHUB2 }}

      # Paso 3: Crear la imagen de Docker desde el Dockerfile en el repositorio
      - name: Build Docker Image
        run: |
          docker build -t karlostcp/my-ecomerce-front:1.0.3 -f Dockerfile .

      # Paso 4: Subir la imagen a Docker Hub
      - name: Push Docker Image
        run: |
          docker push karlostcp/my-ecomerce-front:1.0.3


