name: v10

on:
  push:
    #branches: ["Development"]
    tags: ["v*.*.*"]
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz web de GitHub



env:
  IMAGE_NAME: karlosdocker/my-ecomerce-front
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
  DOCKERFILE_PATH: Dockerfile
  MANUAL_TAG: "v1.0.3"  # Define el tag manual aquí


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: karlostcp
          password: ${{ secrets.MI_PTA_DOCKERHUB2 }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}
            com.docker.image.source.entrypoint=${{ env.DOCKERFILE_PATH }}

      - name: Build and push Docker image on push
        id: build-and-push
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          load: false
          push: true
          tags: ${{ env.MANUAL_TAG }},${{ steps.meta.outputs.tags }}  # Usa el tag manual aquí
          labels: ${{ steps.meta.outputs.labels }}
          platforms: "linux/amd64,linux/arm64"
          sbom: true
          provenance: true
