name: v3

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag for the Docker image (e.g., v1.0.3)"
        required: true
        default: "latest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: karlostcp/my-ecomerce-front  # Docker Hub repository name
      REPO_NAME: karlosdocker/my-ecomerce-front  # GitHub repository name

    steps:
      # Paso 1: Checkout del código del repositorio de GitHub
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: karlosdocker/my-ecomerce-front  # GitHub repo name

      # Paso 2: Login a Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: karlostcp
          password: ${{ secrets.MI_PTA_DOCKERHUB2 }}

      # Paso 3: Construir la imagen de Docker usando el Dockerfile desde el repositorio de GitHub
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ github.event.inputs.version }} -f Dockerfile .

      # Paso 4: Subir la imagen a Docker Hub
      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:${{ github.event.inputs.version }}
